### ISSUE TITLE
Check references to master

### ISSUE THREAD

**Issue by rowannekabalan** [guardian/fezziwig#35]
The master branch of this repository has been migrated to main using the [master-to-main](https://github.com/guardian/master-to-main) tool.

  Some files in the repository contain the word master. Please check the following files and update where required:

  - [x] [README.md](https://github.com/guardian/fezziwig/blob/main/README.md)

**Comment by emdash-ie** [comment]
The readme was updated in https://github.com/guardian/fezziwig/commit/19bb790276ec05198961538809cc83d827f41f3e
